---
title: "679 final"
author: "Chi Zhang"
date: "2021/4/21"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(tidyverse)
library(readxl)
library(keras)
library(rsample)
library(tensorflow)
```

```{r}
tfm <- read.csv("transformed.csv")
```

```{r}
range <- tfm %>% group_by(Site) %>% summarise(max=max(Size),min=min(Size),mean=mean(Size),count=n())
tfm <- tfm %>% group_by(Site) %>% mutate(count=n())
```

```{r}
p<-ggplot(tfm, aes(x=Site, y=Size, fill=Site)) + geom_jitter(aes(colour=Site,alpha=0.5),shape=16, position=position_jitter(0.2)) + geom_boxplot(aes(alpha=0.5),outlier.shape = NA)+ stat_summary(fun.y=mean, colour="black", geom="point", hape=18, size=2,show_guide = FALSE)+ stat_summary(fun.y=mean, colour="black", geom="text", show_guide = FALSE, vjust=-0.7, aes( label=round(..y.., digits=1)))+xlab("Disease Site")+   geom_text(data = tfm, aes(label = count,x = Site, y = 100))
p
```

```{r}
data <- read_csv("seer_data_full.csv")
#data <- data%>%filter(Site.x=="Oropharynx")
#str(data_new)
data <- data%>%mutate_if(is.character,as.factor)
data <- as.data.frame(data)
data_new <- sapply(data,unclass)%>%as.data.frame()

set.seed(100)
train_test_split <- initial_split(data_new, prop = 0.7)
train <- training(train_test_split)
test  <- testing(train_test_split) 
train_y <- as.matrix(train["survive2y"])
test_y <- as.matrix(test["survive2y"])
train_x <- as.matrix(train[,-47])
train_x <-scale(train_x)
test_x <- as.matrix(test[,-47])
test_x <-scale(test_x)
```

```{r}
set_random_seed(42)
one_hot_train_labels <- to_categorical(train_y)
one_hot_test_labels <- to_categorical(test_y)
head(one_hot_train_labels)
model <- keras_model_sequential() %>%
  layer_dense(units = 256, activation = "relu",input_shape = ncol(train_x)) %>%
  layer_dropout(rate = 0.6) %>%
  layer_dense(units = 128, activation = "relu") %>%
  layer_dense(units = ncol(one_hot_train_labels), activation = "sigmoid")

model %>% compile(
  optimizer = "adam",
  loss = "binary_crossentropy",
  metrics = c("accuracy")
)

history <-model %>% fit(train_x, one_hot_train_labels, epochs = 100,batch_size = 512, validation_split = 0.2)
plot(history)
```

```{r}
set_random_seed(42)
model1 <- keras_model_sequential() %>%
  layer_dense(units = 256, activation = "relu",input_shape = ncol(train_x)) %>%
 layer_dropout(rate = 0.6) %>%
  layer_dense(units = 128, activation = "relu") %>%
  layer_dense(units = 2, activation = "sigmoid")

model1 %>% compile(
  optimizer = "adam",
  loss = "binary_crossentropy",
  metrics = c("accuracy")
)

history1 <-model1 %>% fit(train_x, one_hot_train_labels, epochs = 65,batch_size = 512)
results <- model1 %>% evaluate(test_x , one_hot_test_labels)
results
plot(history1)
```

```{r}
pred <-model1%>%predict(test_x)%>%round()
confusionMatrix(as.factor(pred),as.factor(one_hot_test_labels))
```



```{r}
library(caret)
control <- trainControl(method="cv", number=10)
metric <- "Accuracy"
set.seed(7)
fit.rf <- train(as.factor(survive2y)~., data=train, method="rf", metric=metric, trControl=control)
print(fit.rf)
pred1 <-predict(fit.rf,test)
confusionMatrix(as.factor(pred1),as.factor(test$survive2y))

```

