---
title: "SEER-Survival time"
author: "Group 11"
date: "2021/5/3"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(dplyr)
library(scales)
library(readxl)
library(keras)
library(rsample)
library(tensorflow)
library(caret)
```

```{r}
data<-read.csv(file="seer_data_full.csv")
```

#EDA
```{r}
#EDA

## SITE
#median month
data %>% 
group_by(Site.x) %>% 
summarise(AverageSurvivalMonth = median(Survival.months)) %>% 
  ggplot(aes(factor(Site.x), AverageSurvivalMonth, label=AverageSurvivalMonth, fill=factor(Site.x))) +
  geom_col() +
  geom_text(nudge_y = 0.5)

#REGION
ggplot(data, 
       aes(x = Site.x, 
           fill = SEERRegistry)) + 
  geom_bar(position = "stack")

ggplot(data, aes(Site.x))+
  geom_bar(aes(fill=SEERRegistry), position="fill")

#AGE
ggplot(data, aes(Site.x))+
  geom_bar(aes(fill=age_range), position="fill")

#race
ggplot(data, aes(Site.x))+
  geom_bar(aes(fill=Race.x), position="fill")

#survive 2 years
ggplot(data, aes(Site.x))+
  geom_bar(aes(fill=as.factor(survive2y)), position="fill")

ggplot(data, aes(Race.x))+
  geom_bar(aes(fill=as.factor(survive2y)), position="fill")

ggplot(data, aes(age_range))+
  geom_bar(aes(fill=as.factor(survive2y)), position="fill")

ggplot(data, aes(size_range))+
  geom_bar(aes(fill=as.factor(survive2y)), position="fill")

ggplot(data,aes(x=Size.x,fill=as.factor(survive2y),color=as.factor(survive2y),group=as.factor(survive2y)))+
  geom_histogram(aes(y = ..density..), alpha = 0.4,position = position_dodge())+
  geom_line(aes(y = ..density..,), stat = 'density',show.legend = F) 

ggplot(data,aes(x=AgeatDiagnosis,fill=as.factor(survive2y),color=as.factor(survive2y),group=as.factor(survive2y)))+
  geom_histogram(aes(y = ..density..), alpha = 0.4,position = position_dodge())+
  geom_line(aes(y = ..density..,), stat = 'density',show.legend = F)

#DISCRIMIMATION
data$surgery_recommendation<-ifelse(data$Surgery.Decision=="Not recommended"|data$Surgery.Decision=="Not recommended, contraindicated due to other cond; autopsy only (1973-2002)",0,1)

plotdata <- data %>%
  group_by(Race.x, surgery_recommendation) %>%
  summarize(n = n()) %>% 
  mutate(pct = n/sum(n),
         lbl = scales::percent(pct))

ggplot(plotdata, aes(Race.x,pct,fill=as.factor(surgery_recommendation)))+
  geom_bar(stat = "identity",
           position = "fill") +
  geom_text(aes(label = lbl), 
            size = 3, 
            position = position_stack(vjust = 0.5))

##less than 2 years compare more than 2 years
data0<-data%>%filter(survive2y==0)
data1<-data%>%filter(survive2y==1)

#race
ggplot(data0, aes(Race.x))+
  geom_bar(aes(fill=as.factor(SurgeryPerformed.)), position="fill")

ggplot(data1, aes(Race.x))+
  geom_bar(aes(fill=as.factor(SurgeryPerformed.)), position="fill")

#size
ggplot() +
  geom_density(aes(Size.x, fill = "dead_within_2_years"), alpha = .2, data = data0) +
  geom_density(aes(Size.x, fill = "survive_more_than_2_years"), alpha = .2, data = data1) +
  scale_fill_manual(name = "dataset", values = c(survive_more_than_2_years = "red", dead_within_2_years = "green"))

#sex
ggplot() +
  geom_bar(aes(Sex.x, fill = "dead_within_2_years",color="black"), alpha = .2, data = data0) +
  geom_bar(aes(Sex.x, fill = "survive_more_than_2_years",color="black"), alpha = .2, data = data1) +
  scale_fill_manual(name = "dataset", values = c(survive_more_than_2_years = "red", dead_within_2_years = "green"))

#region
plotdata <- data0 %>%
  count(SEERRegistry) %>%
  mutate(pct = n / sum(n),
         pctlabel = paste0(round(pct*100), "%"))


ggplot(plotdata, 
       aes(x = reorder(SEERRegistry, -pct),
           y = pct)) + 
  geom_bar(stat = "identity", 
           fill = "indianred3", 
           color = "black") +
  geom_text(aes(label = pctlabel), 
            vjust = -0.25) +
  scale_y_continuous(labels = percent) +
  labs(x = "Region", 
       y = "Percent", 
       title  = "Percent by region")

plotdata1 <- data1 %>%
  count(SEERRegistry) %>%
  mutate(pct = n / sum(n),
         pctlabel = paste0(round(pct*100), "%"))


ggplot(plotdata1, 
       aes(x = reorder(SEERRegistry, -pct),
           y = pct)) + 
  geom_bar(stat = "identity", 
           fill = "indianred3", 
           color = "black") +
  geom_text(aes(label = pctlabel), 
            vjust = -0.25) +
  scale_y_continuous(labels = percent) +
  labs(x = "Region", 
       y = "Percent", 
       title  = "Percent by region")

#age
ggplot(data0, aes(age_range))+
  geom_bar(aes(fill=as.factor(SurgeryPerformed.)), position="fill")

ggplot(data1, aes(age_range))+
  geom_bar(aes(fill=as.factor(SurgeryPerformed.)), position="fill")

ggplot() +
  geom_density(aes(AgeatDiagnosis, fill = "dead_within_2_years"), alpha = .2, data = data0) +
  geom_density(aes(AgeatDiagnosis, fill = "survive_more_than_2_years"), alpha = .2, data = data1) +
  scale_fill_manual(name = "dataset", values = c(survive_more_than_2_years = "red", dead_within_2_years = "green"))

ggplot(data, aes(x=Site.x, y=Size.x, fill=Site.x)) + geom_jitter(aes(colour=Site.x,alpha=0.5),shape=16, position=position_jitter(0.2)) + geom_boxplot(aes(alpha=0.5),outlier.shape = NA)+ stat_summary(fun.y=mean, colour="black", geom="point", hape=18, size=2,show_guide = FALSE)+ stat_summary(fun.y=mean, colour="black", geom="text", show_guide = FALSE, vjust=-0.7, aes( label=round(..y.., digits=1)))+xlab("Disease Site")+   geom_text(data = data, aes(label = count,x = Site.x, y = 100))
```
#MARY
  
#GUA
  
#CHI
 ```{r}
datac <- data%>%mutate_if(is.character,as.factor)
datac <- as.data.frame(datac)
data_new <- sapply(datac,unclass)%>%as.data.frame()

set.seed(100)
train_test_split <- initial_split(data_new, prop = 0.7)
trainc <- training(train_test_split)
testc  <- testing(train_test_split) 
train_yc <- as.matrix(trainc["survive2y"])
test_yc <- as.matrix(testc["survive2y"])
train_xc <- as.matrix(trainc[,-47])
train_xc <-scale(train_xc)
test_xc <- as.matrix(testc[,-47])
test_xc <-scale(test_xc)
```

```{r}
set_random_seed(42)
one_hot_train_labels <- to_categorical(train_yc)
one_hot_test_labels <- to_categorical(test_yc)
head(one_hot_train_labels)
model <- keras_model_sequential() %>%
  layer_dense(units = 256, activation = "relu",input_shape = ncol(train_xc)) %>%
  layer_dropout(rate = 0.6) %>%
  layer_dense(units = 128, activation = "relu") %>%
  layer_dense(units = ncol(one_hot_train_labels), activation = "sigmoid")

model %>% compile(
  optimizer = "adam",
  loss = "binary_crossentropy",
  metrics = c("accuracy")
)

history <-model %>% fit(train_xc, one_hot_train_labels, epochs = 100,batch_size = 512, validation_split = 0.2)
plot(history)
```

```{r}
set_random_seed(42)
model1 <- keras_model_sequential() %>%
  layer_dense(units = 256, activation = "relu",input_shape = ncol(train_xc)) %>%
 layer_dropout(rate = 0.6) %>%
  layer_dense(units = 128, activation = "relu") %>%
  layer_dense(units = 2, activation = "sigmoid")

model1 %>% compile(
  optimizer = "adam",
  loss = "binary_crossentropy",
  metrics = c("accuracy")
)

history1 <-model1 %>% fit(train_xc, one_hot_train_labels, epochs = 65,batch_size = 512)
results <- model1 %>% evaluate(test_xc, one_hot_test_labels)
results
plot(history1)
```

```{r}
predc <-model1%>%predict(test_xc)%>%round()
confusionMatrix(as.factor(predc),as.factor(one_hot_test_labels))
```

